/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#004395",
        "primary-container": "#2563eb",
        outline: "#737686",
        "surface-bright": "#faf8ff",
        "on-secondary-fixed": "#001a42",
        "on-tertiary-fixed": "#131b2e",
        primary: "#004ac6",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed-variant": "#003ea8",
        background: "#faf8ff",
        tertiary: "#4d556b",
        secondary: "#0058be",
        "secondary-container": "#2170e4",
        "inverse-on-surface": "#f0f0fb",
        "on-secondary-container": "#fefcff",
        "on-tertiary-fixed-variant": "#3f465c",
        "surface-dim": "#d9d9e5",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#e7e7f3",
        "secondary-fixed-dim": "#adc6ff",
        "inverse-surface": "#2e3039",
        "on-primary-container": "#eeefff",
        "surface-container-low": "#f3f3fe",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#191b23",
        "tertiary-container": "#656d84",
        "surface-container": "#ededf9",
        "error-container": "#ffdad6",
        "outline-variant": "#c3c6d7",
        "tertiary-fixed-dim": "#bec6e0",
        "secondary-fixed": "#d8e2ff",
        "on-background": "#191b23",
        "on-error-container": "#93000a",
        "surface-variant": "#e1e2ed",
        "tertiary-fixed": "#dae2fd",
        "surface-tint": "#0053db",
        surface: "#faf8ff",
        "inverse-primary": "#b4c5ff",
        "on-error": "#ffffff",
        "on-tertiary-container": "#eef0ff",
        "on-primary-fixed": "#00174b",
        "surface-container-highest": "#e1e2ed",
        "on-surface-variant": "#434655",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "16px",
        base: "4px",
        "stack-sm": "8px",
        "container-padding": "24px",
        "stack-md": "16px",
        "stack-lg": "32px",
      },
      fontFamily: {
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "data-mono": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};
